// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvgnappjajdlphdywmee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2Z25hcHBqYWpkbHBoZHl3bWVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NjM1NTksImV4cCI6MjA2OTAzOTU1OX0.0zGbAy9Nx2RVtFsMgkGgdhz149wb0Fc83ikenDTWV9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});